defaults:
  - model: Resnet18

#ckpt_path: "/Users/fredvaartnou/Downloads/best.ckpt"

wandb:
  project: "PestSpace"
  entity: "fred-vaartnou-ut"
  run_name: "Resnet18_nocrop"


trainer:
  max_epochs: 15
  accelerator: gpu
  devices: 1

learning_rate: 0.0001

data:
  train_base: "/gpfs/helios/home/fred87/Images/Vicia_faba"
  #train_base: "/Users/fredvaartnou/Library/CloudStorage/OneDrive-TartuÜlikool/PestSpace/Images/Vicia_faba"
  
  num_classes: 2

  classes_to_use:
    - Downy_mildew
    - Chocolate_spot
    #- Rust
  class_to_label:
    Downy_mildew: 0
    Chocolate_spot: 1
    #Rust: 2
  
  batch_size: 32
  num_workers: 4

  use_weightedrandomsampler: false

loss_function:
  use_focal_loss: false
  alpha: [0.309, 0.691]
  gamma: 2

  use_weighted_loss: true
