_target_: models.multiEfficientnetB0.multiEfficientnetB0

model:
  _target_: torchvision.models.efficientnet_b0
  weights: IMAGENET1K_V1
  #weights: null

lr: ${learning_rate}
weight_decay: ${weight_decay}

use_focal_loss: ${loss_function.use_focal_loss}
gamma: ${loss_function.gamma}

use_weighted_loss: ${loss_function.use_weighted_loss}