_target_: models.Resnet18.Resnet18

model:
  _target_: torchvision.models.resnet18
  weights: null
  #weights: IMAGENET1K_V1

num_classes: ${data.num_classes}
lr: ${learning_rate}

use_focal_loss: ${loss_function.use_focal_loss}
alpha: ${loss_function.alpha}
gamma: ${loss_function.gamma}

use_weighted_loss: ${loss_function.use_weighted_loss}